defmodule Valkyrie.Repo.Migrations.AddPapertrail do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:members_versions, primary_key: false) do
      add :user_id,
          references(:users,
            column: :id,
            name: "members_versions_user_id_fkey",
            type: :uuid,
            on_delete: :nothing,
            on_update: :update_all
          )

      add :version_updated_at, :utc_datetime_usec, null: false
      add :version_inserted_at, :utc_datetime_usec, null: false
      add :changes, :map

      add :version_source_id,
          references(:members,
            column: :id,
            name: "members_versions_version_source_id_fkey",
            type: :uuid
          ),
          null: false

      add :version_action_name, :text, null: false
      add :version_action_type, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    drop constraint(:members_versions, "members_versions_version_source_id_fkey")

    drop constraint(:members_versions, "members_versions_user_id_fkey")

    drop table(:members_versions)
  end
end