defmodule Valkyrie.Repo.Migrations.AddTimestamp do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:members) do
      add :created_at, :utc_datetime_usec, null: false
      add :updated_at, :utc_datetime_usec, null: false
    end
  end

  def down do
    alter table(:members) do
      remove :updated_at
      remove :created_at
    end
  end
end