defmodule Valkyrie.Repo.Migrations.AddMembers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:members, primary_key: false) do
      add :is_active, :boolean, null: false
      add :is_manual_entry, :boolean, null: false
      add :ssh_public_key, :text
      add :has_key, :boolean, null: false
      add :tree_name, :text, null: false
      add :xhain_account_id, :bigint, null: false
      add :username, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:members, [:username], name: "members_unique_username_index")
  end

  def down do
    drop_if_exists unique_index(:members, [:username], name: "members_unique_username_index")

    drop table(:members)
  end
end