defmodule Valkyrie.Repo.Migrations.ChangeKeyTargetsToRelational do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:member_key_targets_versions, primary_key: false) do
      add :user_id,
          references(:users,
            column: :id,
            name: "member_key_targets_versions_user_id_fkey",
            type: :uuid,
            on_delete: :nothing,
            on_update: :update_all
          )

      add :version_updated_at, :utc_datetime_usec, null: false
      add :version_inserted_at, :utc_datetime_usec, null: false
      add :changes, :map
      add :version_source_id, :uuid, null: false
      add :version_action_name, :text, null: false
      add :version_action_type, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:member_key_targets, primary_key: false) do
      add :key_target_id,
          references(:key_targets,
            column: :id,
            name: "member_key_targets_key_target_id_fkey",
            type: :uuid,
            on_delete: :delete_all
          ),
          null: false

      add :member_id,
          references(:members,
            column: :id,
            name: "member_key_targets_member_id_fkey",
            type: :uuid,
            on_delete: :delete_all
          ),
          null: false

      add :created_at, :utc_datetime_usec, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:member_key_targets, [:member_id, :key_target_id],
             name: "member_key_targets_unique_access_index"
           )

    create table(:key_targets_versions, primary_key: false) do
      add :user_id,
          references(:users,
            column: :id,
            name: "key_targets_versions_user_id_fkey",
            type: :uuid,
            on_delete: :nothing,
            on_update: :update_all
          )

      add :version_updated_at, :utc_datetime_usec, null: false
      add :version_inserted_at, :utc_datetime_usec, null: false
      add :changes, :map
      add :version_source_id, :uuid, null: false
      add :version_action_name, :text, null: false
      add :version_action_type, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    flush()

    # Backfill the join table from the denormalised `members.key_targets` slug
    # array, then drop the column. Slugs with no matching `key_targets` row are
    # dropped (they were orphaned data that the old model could not enforce).
    backfill_member_key_targets()

    alter table(:members) do
      remove :key_targets
    end
  end

  defp backfill_member_key_targets do
    %{rows: kt_rows} = repo().query!("SELECT id, slug FROM key_targets")
    slug_to_id = Map.new(kt_rows, fn [id, slug] -> {slug, id} end)

    %{rows: member_rows} =
      repo().query!(
        "SELECT id, key_targets FROM members WHERE key_targets IS NOT NULL AND key_targets != '[]'"
      )

    now = DateTime.utc_now() |> DateTime.to_iso8601()

    for [member_id, key_targets_json] <- member_rows,
        slug <- Jason.decode!(key_targets_json),
        key_target_id = Map.get(slug_to_id, slug),
        not is_nil(key_target_id) do
      repo().query!(
        "INSERT INTO member_key_targets (id, member_id, key_target_id, created_at) VALUES (?, ?, ?, ?)",
        [Ecto.UUID.generate(), member_id, key_target_id, now]
      )
    end
  end

  def down do
    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `key_targets_versions` table without the `key_targets_versions_user_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:key_targets_versions)

    drop_if_exists unique_index(:member_key_targets, [:member_id, :key_target_id],
                     name: "member_key_targets_unique_access_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `member_key_targets` table without the `member_key_targets_member_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `member_key_targets` table without the `member_key_targets_key_target_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:member_key_targets)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `member_key_targets_versions` table without the `member_key_targets_versions_user_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:member_key_targets_versions)

    # alter table(:members) do
    # This is the `down` migration of the statement:
    #
    #     remove :key_targets
    #
    # 
    # add :key_targets, {:array, :text}, null: false, default: []
    # end
    # 
  end
end
