defmodule Valkyrie.Repo.Migrations.AddCombinedVersionView do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute """
    CREATE VIEW combined_versions AS
    SELECT id, version_inserted_at, user_id, version_action_name,
           version_action_type, version_source_id, changes,
           version_source_id AS member_id,
           NULL AS key_target_id,
           'member' AS kind
    FROM members_versions
    UNION ALL
    SELECT id, version_inserted_at, user_id, version_action_name,
           version_action_type, version_source_id, changes,
           COALESCE(json_extract(changes, '$.member_id.to'),
                    json_extract(changes, '$.member_id.unchanged'),
                    json_extract(changes, '$.member_id.from')) AS member_id,
           COALESCE(json_extract(changes, '$.key_target_id.to'),
                    json_extract(changes, '$.key_target_id.unchanged'),
                    json_extract(changes, '$.key_target_id.from')) AS key_target_id,
           'access' AS kind
    FROM member_key_targets_versions
    """
  end

  def down do
    execute "DROP VIEW combined_versions"
  end
end
