defmodule Valkyrie.Repo.Migrations.AddMatrixContact do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:members) do
      add :matrix_contact, :text
    end
  end

  def down do
    alter table(:members) do
      remove :matrix_contact
    end
  end
end