name: CI

on:
  pull_request:
    branches:
      - "main"

jobs:
  test:
    uses: ./.github/workflows/_test.yml
    with:
      elixir-version: "1.18.4"
      otp-version: "28.0.1"

  build:
    needs: test
    uses: ./.github/workflows/_docker.yml
    with:
      elixir-version: "1.18.4"
      otp-version: "28.0.1"
      push: false
    secrets: inherit
